service: web-app

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

provider:
  name: aws
  stage: prod
  runtime: nodejs8.10
  region: us-east-1
  environment: ${file(env.yml):${self:provider.stage}}

custom:
  documentation:
    api:
      info:
        title: Web projects boilerplate
    models:
      - name: RefreshAccessTokenRequest
        contentType: 'application/json'
        schema:
          required:
            - refreshToken
          properties:
            refreshToken:
              type: string
      - name: CreateUserRequest
        contentType: 'application/json'
        schema:
          required:
            - email
            - username
            - password
            - recaptcha
          properties:
            email:
              type: string
              format: email
            username:
              type: string
            password:
              type: string
              minLength: 3
            recaptcha:
              type: string
      - name: LoginUserRequest
        contentType: 'application/json'
        schema:
          required:
            - userIdentifier
            - password
          properties:
            userIdentifier:
              type: string
            password:
              type: string
      - name: ForgotPasswordRequest
        contentType: 'application/json'
        schema:
          required:
            - email
            - recaptcha
          properties:
            email:
              type: string
              format: email
            recaptcha:
              type: string
      - name: ContactRequest
        contentType: 'application/json'
        schema:
          required:
            - name
            - email
            - message
            - recaptcha
          properties:
            name:
              type: string
            email:
              type: string
              format: email
            message:
              type: string
            recaptcha:
              type: string

functions:
  authorize:
    handler: src/handlers/authorize.handler
  healthCheck:
    handler: src/functions/healthCheck.main
    events:
      - http:
          path: health-check
          method: post
          cors: true
  contact:
    handler: src/functions/misc.contact
    events:
      - http:
          documentation:
            requestModels:
              'application/json': ContactRequest
          path: misc/contact
          method: post
          cors: true
  login:
    handler: src/functions/auth.login
    events:
      - http:
          documentation:
            requestModels:
              'application/json': LoginUserRequest
          path: auth/login
          method: post
          cors: true
          reqValidatorName: onlyBody
  forgot:
    handler: src/functions/auth.forgot
    events:
      - http:
          documentation:
            requestModels:
              'application/json': ForgotPasswordRequest
          path: auth/forgot_password
          method: post
          cors: true
          reqValidatorName: onlyBody
  logout:
    handler: src/functions/auth.logout
    events:
      - http:
          path: auth/logout
          method: delete
          cors: true
  refreshAccessToken:
    handler: src/functions/auth.refreshAccessToken
    events:
      - http:
          documentation:
            requestModels:
              'application/json': RefreshAccessTokenRequest
          path: auth/refresh_access_token
          method: post
          cors: true
          authorizer: authorize
          reqValidatorName: onlyBody
  createUser:
    handler: src/functions/user.create
    events:
      - http:
          documentation:
            requestModels:
              'application/json': CreateUserRequest
          path: users/create
          method: post
          cors: true
          reqValidatorName: onlyBody

resources:
  Resources:
    onlyBody:
      Type: 'AWS::ApiGateway::RequestValidator'
      Properties:
        Name: 'only-body'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
